sudo: false
language: node_js
node_js:
  - "5"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl --data "gitUrl=git%40github.com%kbukum%2Fbabel-plugin-doc-gen.git" https://doc.esdoc.org/api/create)